# Summary:
# Test if the the GitHub Action builds correctly.
# Makes sure the GitHub Action builds when being built by GitHub Actions.

name: 'Checks if the Action builds correctly'
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  run-build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          yarn
          yarn build:once
