# Summary:
# On a release, automatically update the tag

name: 'GitHub Action tag releases'
on:
  release:
    types: [published, edited]

jobs:
  actions-tagger:
    runs-on: ubuntu-latest
    steps:
      - uses: Actions-R-Us/actions-tagger@2.0.1
        env:
          GITHUB_TOKEN: "${{ github.token }}"
        with:
          publish_latest_tag: true